ITERATION = []
AGENT_TYPE = []
AGENT_NAME = []
AGENT_NUMBER = []
ORIGINAL_SOURCE = []
ORIGINAL_DESTINATION = []
CURRENT_PLACE = []
NEXT_PLACE = []

BLUE_AGENT_CoT = []
RED_AGENT_CoT = []

BLUE_AGENTS_STATUS = []

BLUE_RESPONSE_TO_RED = []
BLUE_RESPONSE_TO_BLUE = []
RED_RESPONSE_TO_BLUE = []
RED_RESPONSE_TO_RED = []

BLUE_AGENT_RESPONSE_JSON = []
RED_AGENT_RESPONSE_JSON = []

BLUE_AGENT_TYPE = []
RED_AGENT_TYPE = []

BLUE_AGENTS = []
RED_AGENTS = []